### ISSUE TITLE
Compatibility with checkpoints from the original implementation

### ISSUE THREAD

**Issue by Simontwice** [Howuhh/faster-trajectory-transformer#2]
Hello!

I am wondering whether the code is compatible with the checkpoints shared in the original repo. I am hoping to play around with this concept, and hope that the checkpoints could be plugged into this implementation seamlessly.

Cheers!

**Comment by Howuhh** [comment]
Hi! Unfortunately, because of the addition of the cache, it is not possible to use checkpoints from the original code. I uploaded a couple of trained to this repository, in order to just have fun you can use them. If you don't want to do any big experiments, I think it's better to use the original code to understand the method itself first and not get confused with additional tricks.

Best of luck!

**Comment by Simontwice** [comment]
Thank you very much for the answer! This clears things up.

A very offtop follow-up: I can't find any setup instructions for your repo - is it the same as the original one?

**Comment by Howuhh** [comment]
You' re right, the instructions just aren't present yet! I'll probably add it when I have some free time, but I think the overlap with the original repository is almost 100% + stable baselines3 and omegaconf

**Comment by Simontwice** [comment]
Right, thanks once again!

**Comment by Howuhh** [comment]
@Simontwice Hi! I saw that you forked the repository. Perhaps you should be aware of the bug from https://github.com/Howuhh/faster-trajectory-transformer/issues/3#issue-1286177514.

**Comment by Simontwice** [comment]
Very much appreciated!
Best,
Szymon


śr., 29 cze 2022 o 11:39 Alexander Nikulin ***@***.***>
napisał(a):
